project_id = "vtdtmhgzisigtqryojwl"

[functions.import-dorms-data]
verify_jwt = true

[functions.roomy-chat]
verify_jwt = false

[functions.send-owner-notification]
verify_jwt = false

[functions.process-pending-notifications]
verify_jwt = false

[functions.create-owner-record]
verify_jwt = true

[functions.log-user-actions]
verify_jwt = true

[functions.train-recommender]
verify_jwt = false

[functions.generate-tour-questions]
verify_jwt = false

[functions.create-admin-profile]
verify_jwt = true

[functions.create-room]
verify_jwt = true
